services:
  postgres:
    image: postgres:18
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped

    ports:
      - "9090:9090"

    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus

    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  postgres_data:
  prometheus_data: