CREATE EXTENSION IF NOT EXISTS pgcrypto;

ALTER TABLE jobs
DROP CONSTRAINT jobs_pkey;

ALTER TABLE jobs
DROP COLUMN id;

ALTER TABLE jobs
ADD COLUMN id UUID NOT NULL DEFAULT gen_random_uuid();

ALTER TABLE jobs
ADD PRIMARY KEY (id);